## https://golangci-lint.run/usage/configuration/

repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    language: golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports ## go install golang.org/x/tools/cmd/goimports@latest
      - id: go-unit-tests
      - id: golangci-lint ## yay -S golangci-lint
        exclude: ^(docs)/