apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: infobae-api-dev
  name: infobae-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: infobae-api-dev
  template:
    metadata:
      labels:
        io.kompose.service: infobae-api-dev
    spec:
      containers:
        - image: dyallo/infobae_api:X64_unstable
          name: infobae-api-dev
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false