apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: infobae-api-dev
  name: infobae-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: infobae-api-dev
  template:
    metadata:
      labels:
        io.kompose.service: infobae-api-dev
    spec:
      containers:
        - image: dyallo/infobae_api:unstable
          name: infobae-api-dev
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
              cpu: 0.5
              ephemeral-storage: 1Gi
      restartPolicy: Always
      automountServiceAccountToken: false
      securityContext:
        allowPrivilegeEscalation: false