apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: infobae-api-dev
  name: infobae-api-dev
spec:
  ports:
    - name: 'tcp'
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: infobae-api-dev
  type: NodePort