apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infobae-api-dev

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
- count: 1
  name: infobae-api

images:
- name: dyallo/infobae_api
  newTag: dev-34d9f06b371cd48c87d8e355856e2af985a929b3
