apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: infobae-api-prod
  name: infobae-api-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: infobae-api-prod
  template:
    metadata:
      labels:
        io.kompose.service: infobae-api-prod
    spec:
      containers:
        - image: dyallo/infobae_api:latest
          name: infobae-api-prod
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
              ephemeral-storage: 1Gi
      restartPolicy: Always
      automountServiceAccountToken: false
      securityContext:
        allowPrivilegeEscalation: false