version: 1.0
runtime: go1
build:
  commands:
    build:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - export PATH=$PATH:$(go env GOPATH)/bin
      - swag init -d src
      - go build -o ./bin/InfobaeAPI ./src/main.go
run:
  command: ./bin/InfobaeAPI