apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: infobae
  name: infobae
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: infobae
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: infobae
    spec:
      containers:
        - image: dyallo/infobae_api
          name: infobae-dev
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - NET_BIND_SERVICE
              drop:
                - ALL
      restartPolicy: Always
