apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infobae-api

resources:
- ../../base

commonLabels:
  environment: prod

replicas:
- count: 2
  name: infobae-api

images:
- name: dyallo/infobae_api
  newTag: master

patches:
- path: service-patch.yaml
  target:
    kind: Service
