apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infobae-api

resources:
- ../../base

commonLabels:
  environment: prod

replicas:
- count: 2
  name: infobae-api

images:
- name: dyallo/infobae_api
  newTag: c5f6e8203c58360424b15ed451471bd139a6c11f

patches:
- path: service-patch.yaml
  target:
    kind: Service
