apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infobae-api

resources:
- ../../base

commonLabels:
  environment: prod

replicas:
- count: 2
  name: infobae-api

images:
- name: dyallo/infobae_api
  newTag: 47e680921792a89a8a2ada41fa136d093c7a4600

patches:
- path: service-patch.yaml
  target:
    kind: Service
