name: Docker Hub Publish

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      file:
        required: true
        type: string
      push:
        required: true
        type: boolean
      tags:
        required: true
        type: string
      platforms:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  publish:
    permissions: 
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Login to Docker Hub
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Build and push ${{ inputs.tags }} on ${{ inputs.platforms }}
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
          platforms: ${{ inputs.platforms }}