name: Docker Publish

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'src/**'
      - 'infra/docker/**'
      - 'infra/kubernetes/**'
      - '.github/workflows/publish.yml'
      - 'tests/**'
  push:
    branches: [ "develop", "master" ]
    paths:
      - 'src/**'
  
env:
  APP_NAME: infobae_api
  APP_VERSION: latest
  APP_DEV_VERSION: unstable

jobs:

  test:
    permissions: 
      contents: read

    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Set up Go
        uses: actions/setup-go@5a083d0e9a84784eb32078397cf5459adecb4c40
        with:
          go-version: 1.23.2

      - name: Test
        run: go test -v ./tests

  develop:
    permissions: 
      contents: read

    needs: test
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/docker.yml
    with:
      context: .
      file: infra/docker/Dockerfile
      tags: ${{ env.APP_NAME }}:X64_${{ env.APP_DEV_VERSION }}
      platforms: linux/amd64,linux/arm64
    secrets:
      docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

  master_amd64:
    permissions: 
      contents: read

    needs: test
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/docker.yml
    with:
      context: .
      file: infra/docker/Dockerfile
      tags: ${{ env.APP_NAME }}:X64_${{ env.APP_VERSION }}
      platforms: linux/amd64,linux/arm64
    secrets:
      docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}