name: Docker Publish

on:
    workflow_run:
      workflows: ["test and publish"]
      types:
        - completed
  
env:
  BRANCH_NAME: ${{ github.ref_name }}
  APP_NAME: infobae_api
  APP_VERSION: latest
  APP_DEV_VERSION: unstable

jobs:
  dev:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push - AMD64 - UNSTABLE
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:X64_${{ env.APP_DEV_VERSION }}
          platforms: linux/amd64
      
      - name: Build and push - ARM64 - UNSTABLE
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/ARM64.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:ARM64_${{ env.APP_DEV_VERSION }}
          platforms: linux/arm64

  prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push - AMD64 - PROD
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:X64_${{ env.APP_VERSION }}
          platforms: linux/amd64

      - name: Build and push - ARM64 - PROD
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/ARM64.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:ARM64_${{ env.APP_VERSION }}
          platforms: linux/arm64