name: Docker Publish

on:
  push:
    branches: ["master"]
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/checkout-setup.yml

  production:
    needs: test
    if: (github.ref_name == 'master' || startsWith(github.ref_name, 'v')) && github.event_name != 'pull_request'
    uses: jd-apprentice/jd-workflows/.github/workflows/deploy.yml@main
    with:
      environment: prod
      image_tag: ${{ github.sha }}
      target_branch: master
      overlay_path: overlays/prod
      app_name: infobae_api
      dockerfile_path: infra/docker/Dockerfile
      commit_message: "chore: update image tag to ${{ github.sha }}"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}