name: test and publish

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "master" ]
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      ## TODO: ADD STEPS

  release:
    uses: jd-apprentice/jd-workflows/.github/workflows/release.yml@main
    needs: [test]
    if: github.ref == 'refs/heads/master'
    with:
      name: test, analyze and publish
      runs_on: ubuntu-latest
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}