name: test and publish

on:
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    uses: jd-apprentice/jd-workflows/.github/workflows/release.yml@main
    if: github.ref == 'refs/heads/master'
    with:
      name: create release
      runs_on: ubuntu-latest
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}